from colors import * #import all from colors.py module

#Commands Function
def about():
    print(RED, "Commands show a list of most used commands ")
def user_commands():
    print(REDBOLD, "User")
    print(WHITEBOLD, "id", WHITE, "         -  Print real and effective user and group IDs")
    print(WHITEBOLD, "last", WHITE, "       -  Show a listing of last logged in users")
    print(WHITEBOLD, "lastb", WHITE, "      -  Show a log of the /var/log/btmp file, which contains all the bad login attempts")
    print(WHITEBOLD, "pinky", WHITE, "      -  Show some information about the currently logged in users on system")
    print(WHITEBOLD, "rwho", WHITE, "       -")
    print(WHITEBOLD, "su", WHITE, "         -")
    print(WHITEBOLD, "sudo", WHITE, "       -  Super User Do")
    print(WHITEBOLD, "w", WHITE, "          -  Show who is logged on and what they are doing")
    print(WHITEBOLD, "who", WHITE, "        -  Print information about users who are currently logged in")
    print(WHITEBOLD, "whoami", WHITE, "     -  Print the user name associated with the current effective user id")
    print(WHITEBOLD, "passwd, chmod, chgrp, kill, dmesg")
def console_commands():
    print(REDBOLD, "Console")
    print(WHITEBOLD, "alias", WHITE, "      -  Define new alias and show it")
    print(WHITEBOLD, "awk", WHITE, "        -  Pattern")   
    print(WHITEBOLD, "clear", WHITE, "      -  Clear the terminal screen")
    print(WHITEBOLD, "echo", WHITE, "       -  Write arguments to the standard output")
    print(WHITEBOLD, "exit", WHITE, "       -  Exit from the current shell")
    print(WHITEBOLD, "grep", WHITE, "       -  Match patterns")
    print(WHITEBOLD, "help", WHITE, "       -  Display information about builtin commands")
    print(WHITEBOLD, "history", WHITE, "    -  Display or manipulate the history list")
    print(WHITEBOLD, "man", WHITE, "        -  An interface to the system reference manuals")
    print(WHITEBOLD, "printenv", WHITE, "   -  Print all or part of environment")
    print(WHITEBOLD, "source", WHITE, "     -  Run commands from a file in the current shell")
    print(WHITEBOLD, "tty", WHITE, "") 
    print(WHITEBOLD, "unalias", WHITE, "    -  Remove each name from the list of defined aliases")
def network_commands():
    print(REDBOLD, "Network")
    print(WHITEBOLD, "arp-scan", WHITE, "   -  ...")
    print(WHITEBOLD, "elinks", WHITE, "     -  Lynx-like alternative character mode WWW browser")
    print(WHITEBOLD, "bmon", WHITE, "       -  ..")
    print(WHITEBOLD, "host", WHITE, "       -  ")
    print(WHITEBOLD, "ip", WHITE, "         -  Show / manipulate routing, network devices, interfaces and tunnels ")
    print(WHITEBOLD, "nc", WHITE, "         -  ")
    print(WHITEBOLD, "netstat", WHITE, "    -  Listening port")
    #netstat -pnltu
    print(WHITEBOLD, "nmap", WHITE, "       -  Network scanner")
    print(WHITEBOLD, "nslookup", WHITE, "   -  Show domain information")
    print(WHITEBOLD, "ping", WHITE, "       -  Send ICMP ECHO_REQUEST to network hosts")
    print(WHITEBOLD, "ssh", WHITE, "        -  OpenSSH remote login client")
    print(WHITEBOLD, "telnet", WHITE, "     -  User interface to the TELNET protocol")
    print(WHITEBOLD, "whois", WHITE, "      -  Show advaced details about a domain")
def filesystem_commands():
    print(REDBOLD, "File System")
    print(WHITEBOLD, "cat", WHITE, "        -  Concatenate files and print on the standard output")
    print(WHITEBOLD, "cp", WHITE, "         -  Copy files and directories")
    print(WHITEBOLD, "cd", WHITE, "         -  Change directory to some other location")
    print(WHITEBOLD, "df", WHITE, "         -  Display the disk space used in the file system")
    print(WHITEBOLD, "du", WHITE, "         -  Disk Usage")
    print(WHITEBOLD, "fdisk", WHITE, "      -  ")
    print(WHITEBOLD, "file", WHITE, "       -  Determine file type ")
    print(WHITEBOLD, "find", WHITE, "       -  Search for files in a directory hierarchy")
    #find /path/ -type f -name file-to-search
    print(WHITEBOLD, "head", WHITE, "       -  Output the first part of files")
    print(WHITEBOLD, "mkdir", WHITE, "      -  Make a directory, if they do not already exist")
    print(WHITEBOLD, "nano", WHITE, "       -  Nano's ANOther editor, command line text editor inspired by Pico (Unix-like)")
    print(WHITEBOLD, "pwd", WHITE, "        -  Print name of current/working directory")
    print(WHITEBOLD, "tail", WHITE, "       -  Output the last part of files")
    print(WHITEBOLD, "touch", WHITE, "      -  Create a new, empty file, or update the modified time of an existing one")
    print(WHITEBOLD, "tree", WHITE, "       -  List contents of directories in a tree-like format")
    print(WHITEBOLD, "rm", WHITE, "         -  Remove files or directories")
    print(WHITEBOLD, "rmdir", WHITE, "      -  Remove empty directories")
    print(WHITEBOLD, "wc", WHITE, "         -  Print newline, word, and byte counts for each file")
    print("mount umount")
def system_commands():
    print(REDBOLD, "System")
    print(WHITEBOLD, "crontab", WHITE, "    -  The crontab is used to automate all types of tasks on Linux systems")
    print(WHITEBOLD, "cal", WHITE, "        -  Displays a calendar")
    print(WHITEBOLD, "date", WHITE, "       -  Print or set the system date and time")
    print(WHITEBOLD, "free", WHITE, "       - ...")
    print(WHITEBOLD, "hostaname", WHITE, "  -  Show or set the system's host name")
    print(WHITEBOLD, "htop", WHITE, "       -  Display Linux processes in interactive mode")
    print(WHITEBOLD, "journalctl", WHITE, " -  Query the systemd journal")
    print(WHITEBOLD, "lsb_release", WHITE, "-  Show distribution-specific information from /etc/os/release")
    print(WHITEBOLD, "lscpu", WHITE, "      -  Display information about the CPU architecture")
    print(WHITEBOLD, "lspci")
    print(WHITEBOLD, "reboot", WHITE, "     -  Restart the machine")
    print(WHITEBOLD, "service", WHITE, "    - ")
    print(WHITEBOLD, "shutdown", WHITE, "   -  Power off the machine")
    print(WHITEBOLD, "systemctl", WHITE, "  -  Control the systemd system and service manager")
    print(WHITEBOLD, "top", WHITE, "        -  Display Linux processes")
    print(WHITEBOLD, "type", WHITE, "       -  Display information about command type")
    print(WHITEBOLD, "uname", WHITE, "      -  Print system information")
    print(WHITEBOLD, "uptime", WHITE, "     -  Tell how long the system has been running")
    print(WHITEBOLD, "whereis", WHITE, "    -  Locate the binary, source, and manual page files for a command")
    print(WHITEBOLD, "which", WHITE, "      -  Locate the binary")
def show():
    user_commands()
    print("")
    console_commands()
    print("")
    network_commands()
    print("")
    filesystem_commands()
    print("")
    system_commands()
def list():
    print("[system, users, network, filesystem, packet]")
